language: ruby
sudo: false
cache: bundler
before_script:
  - psql -c 'create database feed_the_hungry_test;' -U postgres
env:
  - DATABASE_URL=postgresql://localhost/feed_the_hungry_test

script: |
  bundle exec hanami db prepare
  bundle exec rubocop
  bundle exec rake spec --trace

rvm:
  - 2.6

services:
  - postgresql
